// frontend/src/app/pages/register-page/register-page.component.ts
import { Component } from '@angular/core';
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { User } from '../../models/User';
import { AuthService } from '../../services/auth/auth.service';
import { TokenService } from '../../services/token/token.service';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-register-page',
  standalone: true,
  imports: [RouterLink, ReactiveFormsModule],
  templateUrl: './register-page.component.html',
  styleUrl: './register-page.component.css',
})
export class RegisterPageComponent {
  constructor(
    private authService: AuthService,
    private tokenService: TokenService,
    private router: Router
  ) {
    if (tokenService.isLogedIn()) {
      router.navigateByUrl('/');
    }
  }

  registerForm = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', Validators.required),
  });

  user: User = new User('', '');
  errorMessage: string = '';

  public handleSubmit(): void {
    this.user = new User(
      this.registerForm.value.email,
      this.registerForm.value.password
    );
    this.register(this.user);
  }

  private register(user: User): void {
    this.authService.register(user).subscribe(
      (token: string) => {
        if (token != '') {
          this.tokenService.setToken(token);
          this.router.navigateByUrl('/');
          this.refreshPage();
        }
      },
      (error: HttpErrorResponse) => {
        console.log(error);
        this.errorMessage = error.error.detail;
      }
    );
  }

  private refreshPage(): void {
    setInterval(() => {
      location.reload();
    }, 300);
  }
}

<div class="container">
  <h1>Nie masz konta?</h1>
  <h2>Zarejestruj się!</h2>
  <form [formGroup]="registerForm" (ngSubmit)="handleSubmit()">
    <input formControlName="email" type="email" placeholder="Email address" />
    <input formControlName="password" type="password" placeholder="Password" />
    @if (errorMessage != '') {
    <div class="error-box">
      <span>{{ errorMessage }}</span>
    </div>
    }
    <button
      type="submit"
      [disabled]="!registerForm.valid"
      [class]="{ 'disabled-button': !registerForm.valid }"
    >
      Zarejestruj
    </button>
  </form>
  <div class="reminder">
    <a routerLink="/login">Zaloguj</a>
  </div>
</div>

// astrosales-frontend/src/pages/register/RegisterPage.jsx
import React, { useContext, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../../components/auth-context/AuthContext";
import AuthService from "../../services/auth/AuthService";
import styles from "./RegisterPage.module.css";

const RegisterPage = () => {
  const authService = new AuthService();

  const [registerForm, setRegisterForm] = useState({ email: "", password: "" });
  const [formValid, setFormValid] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const { login } = useContext(AuthContext);
  const navigate = useNavigate();

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(registerForm);
    authService
      .register(registerForm)
      .then((res) => {
        if (res.status == 400) {
          setErrorMessage(res.detail);
          return;
        }
        alert("Konto utworzone pomyślnie.");
        login(res.token);
        console.log("success");
        navigate("/");
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const validateForm = () => {
    if (registerForm.email !== "" && registerForm.password !== "") {
      setFormValid(true);
    } else {
      setFormValid(false);
    }
    console.log(formValid);
  };

  const handleChange = (event) => {
    const { name, value } = event.target;
    setRegisterForm({ ...registerForm, [name]: value });
    validateForm();
    setErrorMessage("");
  };

  return (
    <div className={styles.container}>
      <h1>Nie masz konta?</h1>
      <h2>Zarejestruj się!</h2>
      <form onSubmit={handleSubmit}>
        <input
          type="email"
          name="email"
          value={registerForm.email}
          onChange={handleChange}
          placeholder="Adres email"
        />
        <input
          type="password"
          name="password"
          value={registerForm.password}
          onChange={handleChange}
          placeholder="Hasło"
        />
        <p className={styles.errorBox}>{errorMessage}</p>
        <button
          type="submit"
          className={!formValid ? styles.disabledButton : ""}
        >
          Zarejestruj
        </button>
      </form>
      <div className={styles.reminder}>
        <Link to={"/login"}>Zaloguj</Link>
      </div>
    </div>
  );
};

export default RegisterPage;
