// astrosales-frontend/src/pages/login/LoginPage.jsx
import React, { useContext, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../../components/auth-context/AuthContext";
import AuthService from "../../services/auth/AuthService";
import style from "./LoginPage.module.css";

const LoginPage = () => {
  const authService = new AuthService();
  const { login } = useContext(AuthContext);

  const [loginForm, setLoginForm] = useState({
    email: "",
    password: "",
  });

  const [errorMessage, setErrorMessage] = useState("");
  const navigate = useNavigate();

  const handleSubmit = (event) => {
    event.preventDefault();
    if (loginForm.email === "" || loginForm.password === "") {
      setErrorMessage("Email i hasło nie może być puste.");
    } else {
      setErrorMessage("");
      authService.login(loginForm).then((res) => {
        if (res.status === 404 || res.status === 400) {
          setErrorMessage(res.detail);
        } else {
          login(res.token);
          console.log("success");
          navigate("/");
        }
      });
    }
  };

  const handleChange = (event) => {
    const { name, value } = event.target;
    setLoginForm({ ...loginForm, [name]: value });
  };

  return (
    <div className={style.container}>
      <h1>Masz już konto?</h1>
      <h2>Zaloguj się!</h2>
      <form onSubmit={handleSubmit}>
        <input
          type="email"
          name="email"
          value={loginForm.email}
          onChange={handleChange}
          placeholder="Adres email"
        />
        <input
          type="password"
          name="password"
          value={loginForm.password}
          onChange={handleChange}
          placeholder="Hasło"
        />
        {errorMessage && (
          <div className={style.errorBox}>
            <span>{errorMessage}</span>
          </div>
        )}
        <button type="submit">Zaloguj</button>
      </form>
      <div className={style.reminder}>
        <Link to={"#"}>Zapomniałeś hasła?</Link>
        <Link to={"/register"}>Zarejestruj</Link>
      </div>
    </div>
  );
};

export default LoginPage;

// frontend/src/app/pages/login-page/login-page.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { User } from '../../models/User';
import { AuthService } from '../../services/auth/auth.service';
import { TokenService } from '../../services/token/token.service';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [RouterLink, ReactiveFormsModule],
  templateUrl: './login-page.component.html',
  styleUrl: './login-page.component.css',
})
export class LoginPageComponent {
  loginForm = new FormGroup({
    email: new FormControl(''),
    password: new FormControl(''),
  });

  constructor(
    private authService: AuthService,
    private router: Router,
    private tokenService: TokenService
  ) {
    if (tokenService.isLogedIn()) {
      router.navigateByUrl('/');
    }
  }

  user: User = new User('', '');
  errorMessage: string = '';

  public handleSubmit() {
    this.user = new User(
      this.loginForm.value.email,
      this.loginForm.value.password
    );
    this.authenticate(this.user);
  }

  public authenticate(user: User): void {
    this.authService.authenticate(user).subscribe(
      (token: string) => {
        if (token != '') {
          this.router.navigateByUrl('/');
          this.tokenService.setToken(token);
          this.refreshPage();
          // issue: token is not remove after refreshPage()
        }
      },
      (error: HttpErrorResponse) => {
        console.log(error);
        this.errorMessage = error.error.detail;
      }
    );
  }

  private refreshPage(): void {
    setTimeout(() => {
      location.reload();
    }, 100);
  }
}

<div class="container">
  <h1>Masz już konto?</h1>
  <h2>Zaloguj się!</h2>
  <form [formGroup]="loginForm" (ngSubmit)="handleSubmit()">
    <input type="email" formControlName="email" placeholder="Email address" />
    <input type="password" formControlName="password" placeholder="Password" />
    @if (errorMessage != '') {
    <div class="error-box">
      <span>{{ errorMessage }}</span>
    </div>
    }
    <button type="submit">Zaloguj</button>
  </form>
  <div class="reminder">
    <a href="#">Zapomniałeś hasła?</a>
    <a routerLink="/register"> Zarejestruj</a>
  </div>
</div>
