// frontend/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TokenService } from '../../services/token/token.service';
@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  providers: [TokenService],
})
export class HeaderComponent {
  userDetails: any = {};
  isLoggedIn: boolean = false;
  isAdmin: boolean = false;

  constructor(private tokenService: TokenService) {
    if (tokenService.isLogedIn()) {
      this.isLoggedIn = true;
      let token: any = sessionStorage.getItem('token');
      this.userDetails = tokenService.getRolesAndIdFromToken(token);
      if (token && this.userDetails.roles.includes('ROLE_ADMIN')) {
        this.isAdmin = true;
      }
    }
  }

  public logout(): void {
    this.tokenService.logOut();
  }
}

<header>
  <div class="container">
    <a class="logo" routerLink="/">AstroSales</a>
    <nav>
      <ul>
        <li><a routerLink="/flights">Loty</a></li>
        @if (isLoggedIn) { @if (isAdmin) {
        <li><a routerLink="/admin">Panel</a></li>
        } @else {
        <li><a routerLink="/account">Konto</a></li>
        }
        <li><a href="#" (click)="logout()">Wyloguj</a></li>
        } @else {
        <li>
          <a routerLink="/login">Zaloguj się</a>
        </li>
        }
      </ul>
    </nav>
  </div>
</header>

// astrosales-frontend/src/components/header/Header.jsx
import React, { useContext } from "react";
import { Link } from "react-router-dom";
import { AuthContext } from "../auth-context/AuthContext";
import styles from "./Header.module.css";

const Header = () => {
  const title = "AstroSales";

  const { isLoggedIn, isAdmin, logout } = useContext(AuthContext);

  return (
    <header className={styles.header}>
      <div className={styles.container}>
        <Link to={"/"} className={styles.logo}>
          {title}
        </Link>
        <nav className={styles.nav}>
          <ul className={styles.navList}>
            <li className={styles.navItem}>
              <Link to={"/flights"} className={styles.navLink}>
                Loty
              </Link>
            </li>
            {isAdmin && (
              <li className={styles.navItem}>
                <Link to={"/admin"} className={styles.navLink}>
                  Panel
                </Link>
              </li>
            )}
            {isLoggedIn ? (
              <>
                <li className={styles.navItem}>
                  <Link to={"/account"} className={styles.navLink}>
                    Konto
                  </Link>
                </li>
                <li className={styles.navItem}>
                  <Link to={"#"} className={styles.navLink} onClick={logout}>
                    Wyloguj
                  </Link>
                </li>
              </>
            ) : (
              <li className={styles.navItem}>
                <Link to={"/login"} className={styles.navLink}>
                  Zaloguj
                </Link>
              </li>
            )}
          </ul>
        </nav>
      </div>
    </header>
  );
};

export default Header;
