// frontend/src/app/profile/profile.component.ts
import { Component } from '@angular/core';
import { UserProfileService } from '../services/userProfile/user-profile.service';
import { TokenService } from '../services/token/token.service';
import { UserProfile } from '../models/UserProfile';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.css',
  providers: [UserProfileService, TokenService],
})
export class ProfileComponent {
  userProfile?: UserProfile;

  authToken: any = sessionStorage.getItem('token');
  token: any = {};

  constructor(
    private userProfileService: UserProfileService,
    private tokenService: TokenService
  ) {
    this.token = tokenService.getRolesAndIdFromToken(this.authToken);
    if (this.token != null) {
      this.getProfile();
    }
  }

  private getProfile(): void {
    this.userProfileService.getUserProfile(this.token.id).subscribe(
      (userProfile: UserProfile) => {
        this.userProfile = userProfile;
        console.log(this.userProfile);
      },
      (error: HttpErrorResponse) => {
        console.log(error);
      }
    );
  }
}

<div class="container">
  <form [formGroup]="profileForm" (ngSubmit)="handleSubmit()">
    <label for="firstName">Imię:</label>
    <input
      type="text"
      id="firstName"
      formControlName="firstName"
      [placeholder]="userProfileWithId.firstName"
    />

    <label for="lastName">Nazwisko:</label>
    <input
      type="text"
      id="lastName"
      formControlName="lastName"
      [placeholder]="userProfileWithId.lastName"
    />

    <label for="phoneNumber">Telefon:</label>
    <input
      type="tel"
      id="phoneNumber"
      formControlName="phoneNumber"
      [placeholder]="userProfileWithId.phoneNumber"
    />

    <button
      type="submit"
      [disabled]="profileForm.invalid"
      [class]="{ 'disabled-button': profileForm.invalid }"
    >
      Zapisz
    </button>
  </form>
</div>

// astrosales-frontend/src/components/profile/Profile.jsx
import React, { useEffect, useState } from "react";
import ProfileService from "../../services/profile/ProfileService";
import Loader from "../loader/Loader";
import styles from "./Profile.module.css";

const Profile = ({ userId }) => {
  const profileService = new ProfileService();

  const [userProfile, setUserProfile] = useState({});
  const [isLoading, setIsLoading] = useState(true);

  const [profileForm, setProfileForm] = useState({
    firstName: "",
    lastName: "",
    phoneNumber: "",
  });

  useEffect(() => {
    const getUserProfile = () => {
      setIsLoading(true);
      profileService
        .getUserProfile(userId)
        .then((profile) => {
          setUserProfile(profile);
          setIsLoading(false);
        })
        .catch((err) => {
          console.log(err);
          setIsLoading(false);
        });
    };

    setTimeout(getUserProfile, 300);
  }, [userId]);

  const handleChange = (e) => {
    const { id, value } = e.target;
    setProfileForm((prevState) => ({
      ...prevState,
      [id]: value,
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log("Form submitted");
    profileService
      .partialUpdate(userProfile.id, profileForm)
      .then((res) => {
        setUserProfile(res);
        clearProfileForm();
        alert("Profil zaktualizowany");
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const clearProfileForm = () => {
    setProfileForm({
      firstName: "",
      lastName: "",
      phoneNumber: "",
    });
  };

  if (isLoading) {
    return <Loader />;
  }

  return (
    <div className={styles.container}>
      <form onSubmit={handleSubmit}>
        <label htmlFor="firstName">Imię:</label>
        <input
          type="text"
          id="firstName"
          value={profileForm.firstName}
          onChange={handleChange}
          placeholder={userProfile.firstName}
        />

        <label htmlFor="lastName">Nazwisko:</label>
        <input
          type="text"
          id="lastName"
          value={profileForm.lastName}
          onChange={handleChange}
          placeholder={userProfile.lastName}
        />

        <label htmlFor="phoneNumber">Telefon:</label>
        <input
          type="tel"
          id="phoneNumber"
          value={profileForm.phoneNumber}
          onChange={handleChange}
          placeholder={userProfile.phoneNumber}
        />

        <button type="submit">Zapisz</button>
      </form>
    </div>
  );
};

export default Profile;
